### ISSUE TITLE
Scrollbar gets offset to the right in windowed screen mode

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2CommunityPromotionScreen#19]

**Comment by Iridar** [comment]
This should be done after #13

**Comment by pledbrook** [comment]
I just read this comment in one of @kdm2k6's PRs:

> 	// KDM : When the scrollbar was anchored, it would move around when switching from 'fullscreen' mode
>	// to 'windowed' mode. Consequently, anchoring has been removed, and its X location has been updated
>	// so that it remains on the right side of the promotion screen.

Is that what this issue is about?

**Comment by Iridar** [comment]
Sounds pretty close, yeah

**Comment by pledbrook** [comment]
I think we just implement this based on the fix in #13 rather than waiting on that issue

**Comment by Iridar** [comment]
I don't mind, but the scrollbar was also bugged in the opposite direction in both windowed and fullscreen when I checked out #13's code.
