### ISSUE TITLE
Allow mods to override or add their own constraints on whether abilities can be picked

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2CommunityPromotionScreen#3]
`NPSBDP_UIArmory_PromotionHero.CanPurchaseAbility()` is currently hard coded in terms of the constraints that limit whether a soldier can purchase an ability or not. We should add a hook that allows mods to either override or add their own constraints to that default behaviour.

**Comment by ChrisTheThinMint** [comment]
To add to this, the hook should also be able to patch ability localization, just like how ability prerequisites are already noted. Any mod that adds custom logic will likely want to inform the player about the requirements for the perk. Simply being able to pass a string should suffice.

**Comment by pledbrook** [comment]
But prerequisites are just marked with the connecting line, right? The promotion screen doesn't currently display the reason that abilities can't be picked as far as I can tell.

**Comment by pledbrook** [comment]
@ChrisTheThinMint I think that's an orthogonal concern that just impacts this issue as well, so I've raised it as a separate one (#7), particularly as it should also work for the current hard-coded constraints.
