### ISSUE TITLE
Show more-info icon for all revealed abilities

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2CommunityPromotionScreen#42]
The little yellow '?' only appears for abilities that are not locked. That's fine if you're hiding the locked abilities, but if you have the `RevealAllAbilities` config option set, for example, it makes no sense to disallow players from seeing the extra information about the currently-locked abilities.

**Comment by pledbrook** [comment]
I implemented something like this in a [LWOTC commit](https://github.com/long-war-2/lwotc/commit/551530b2b46aa12be7d39e47aa0a223fd9a711d2#diff-76a0fafaba81eca85a813285b6f238a10818144301d062f8e6920fdc532a347c), but it only checks whether `RevealAllAbilities` is set. A more appropriate solution may simply be to check whether the player can see the ability, i.e. it's not hidden.

**Comment by Iridar** [comment]
Makes sense. Let's handle this after #45 is dealt with so there's no merge conflict with the _Column class.

**Comment by pledbrook** [comment]
I don't think this needs to wait on a PR that isn't finalised and is in a minor state of limbo right now. It will be fine to rebase #45 when we've found and agreed upon a solution for it. Plus it may not even have changes to the hero column class once it's done.

**Comment by Iridar** [comment]
Alright, I'll handle it.

**Comment by Iridar** [comment]
Addressed in https://github.com/X2CommunityCore/X2CommunityPromotionScreen/commit/1f270fdfe4ef33c8a6f242781d45f1e5b6111275

Performed sufficient testing to make sure it works without issues.
