### ISSUE TITLE
Allow mods to influence or react to players selecting abilities

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2CommunityPromotionScreen#43]
An ability isn't selected until it is confirmed by the dialog, but I'm not sure it's possible for mods to interact with it in any meaningful way. We should override the callback function and provide one or two access points for mods so that they can react when an ability is selected/purchased.

Example use case: LWOTC has its own callback function that adds unit value to the current soldier that tracks how many abilities have been purchased outside of normal promotions. This is to make it more and more expensive to purchase multiple class abilities at any rank, encouraging the AP to be spent across multiple soldiers rather than just into the A team.

**Comment by pledbrook** [comment]
Depends on PR #41, which adds the custom callback function.

**Comment by Iridar** [comment]
I like it. I thought that it's the #41 that will be adding the entry points, didn't see any and got confused. I'll go merge #41 then.
