### ISSUE TITLE
Pass `CanSpendAP()` result with override events

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2CommunityPromotionScreen#46]
Listeners that override the behaviour of the promotion screen will often want to know whether the player is able to spend AP, since it's a key component of whether abilities can be purchased.

At the very least, 'OverrideCanPurchaseAbility' should pass the result of `CanSpendAP()` in the tuple.

**Comment by Iridar** [comment]
Sure, I don't mind, let's add lots of data to the event. However, I'm proposing a certain change in convention. CHL events traditionally have the following order of arguments in event tuples: in -> inout -> out. 

I'm suggesting we reverse that convention, and go inout -> out -> in. That will let us freely add "in" properties to the tuple without upsetting the order.

**Comment by pledbrook** [comment]
I'm fine with that, although I don't know if it's more common to want to add `in` properties rather than `out` or `inout` ones.

**Comment by Iridar** [comment]
Well it seems to be needed in the case of OverrideAPCost and OverrideCanPurchase ability events, as there is only really 1-2 out/inout properties , and a ton of additional `in` properties that we may or may not want to add depending what specific mods require. I'll reverse the order and add the result of CanSpendAP() then.

**Comment by Iridar** [comment]
Addressed in https://github.com/X2CommunityCore/X2CommunityPromotionScreen/commit/5db9ff8ec67579f75fd8e4f887ce7a960957dc11
