### ISSUE TITLE
Inconsistent behavior when opening promotion screen from squad select

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2CommunityPromotionScreen#56]
When done so, certain perks on first two rows display as having zero cost. When the promotion screen is opened normally, everything works as expected.

https://cdn.discordapp.com/attachments/501409129236267029/862617489425956874/20210708165153_1.jpg

**Comment by Iridar** [comment]
Apparently the issue is isolated to this "ability points" button on RJSS:

https://cdn.discordapp.com/attachments/501409129236267029/863075147506647050/unknown.png

**Comment by Iridar** [comment]
I couldn't reproduce the problem.

**Comment by robojumper** [comment]
Potentially related: robojumper/robojumperSquadSelect#11

**Comment by Iridar** [comment]
> Potentially related: [robojumper/robojumperSquadSelect#11](https://github.com/robojumper/robojumperSquadSelect/pull/11)

Looks like it was merged, though?

**Comment by Iridar** [comment]
Ohhh we need to set the config flag

**Comment by Iridar** [comment]
I relayed this to the person who could replicate the problem, they'll let me know if that was it. I'd expect this is the problem, and the flag definitely looks like something we want to be setting. Thanks for letting me know.

**Comment by Iridar** [comment]
This was indeed the cause.

**Comment by Iridar** [comment]
Fixed by commit https://github.com/X2CommunityCore/X2CommunityPromotionScreen/commit/d8982c5903f9312af795b7ce56804fff1b13e27c
