### ISSUE TITLE
Ability preview is sometimes incorrect

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2CommunityPromotionScreen#64]
[Example image.](https://cdn.discordapp.com/attachments/590853806175158272/866352569130156042/20210718121039_1.jpg)

> Notice how the Fan Fire icon is highlighted, but the ability description at the bottom is for Close Encounters, the ability above it.

[Blamed line of code.](https://github.com/X2CommunityCore/X2CommunityPromotionScreen/blob/master/X2WOTCCommunityPromotionScreen/Src/X2WOTCCommunityPromotionScreen/Classes/CPS_UIArmory_PromotionHeroColumn.uc#L204)

> does not convert an icon index to an ability index/branch, which is what PreviewAbility() expects.

**Comment by Iridar** [comment]
This has been confirmed as existing in NPSBD itself, and the "blamed line of code" doesn't seem to have anything to do with it.

The issue likely occurs somewhere in [this function](https://github.com/X2CommunityCore/X2CommunityPromotionScreen/blob/823b1cbc044fba20b931c699fc2b176a3b5198e3/X2WOTCCommunityPromotionScreen/Src/X2WOTCCommunityPromotionScreen/Classes/CPS_UIArmory_PromotionHero.uc#L1189).

**Comment by pledbrook** [comment]
I can't reproduce this with the latest code. I'm wondering if it was fixed as part of a refactor that just wasn't in the CPS I distributed with.

**Comment by Iridar** [comment]
Probably not, the refactor only touched the ability tagging and _properties events. Let's keep an ear to the ground on this one.

**Comment by Iridar** [comment]
Couldn't replicate this either, and considering this issue hasn't come up again all this time, I'm closing it.
