### ISSUE TITLE
Better handling for soldiers with less than 7 Ranks.

### ISSUE THREAD

**Issue by h4ilst0rm** [X2CommunityCore/X2CommunityPromotionScreen#74]
Currently any soldier with less than 7 ranks will have its squaddie perks repeated to fill the remaining ranks.

This looks very confusing when view locked skills option is enabled. Having them locked is a bit better, but still quite misleading as the soldier can not promote to obtain those skills.
![Xcom 2_2021 11 15-19 18](https://user-images.githubusercontent.com/59488828/141827754-442cc601-8c0b-422a-8a6c-f4bea2d7b6ea.png)

The original 2 column UI handles it the best, the 7th rank row is simply not created there.
![Xcom 2_2021 11 15-19 19](https://user-images.githubusercontent.com/59488828/141827841-1a10f6ad-c29f-414a-9bb4-e9d407dc115e.png)

The vanilla training center UI handles it in my opinion better than CPS, as there are no misleading perk icons. The rank icon and text are clearly broken though.
![Xcom 2_2021 11 15-19 20](https://user-images.githubusercontent.com/59488828/141828054-5198f7b4-0594-4c87-a902-8fa8353ef65e.png)

The situation gets worse the more ranks are missing. For example a SPARK with no class abilites beyond the first ones:
![Xcom 2_2021 11 15-19 27](https://user-images.githubusercontent.com/59488828/141828131-7535c1ac-2113-460e-9845-a3d9fd8b24e2.png)

In my opinion the desired behaviour would be to not have any extra ability icons beyond what the soldier actually has.

**Comment by Iridar** [comment]
This is a valid problem. If you make a PR to fix it I'll be happy to review it.

**Comment by h4ilst0rm** [comment]
PR is up

**Comment by Iridar** [comment]
PR merged, closing.
