### ISSUE TITLE
When promoting reaper, I get a CTD

### ISSUE THREAD

**Issue by Sir1Twist** [X2CommunityCore/X2CommunityPromotionScreen#77]
I seem to get a CTD when using this mod, and promoting a reaper. Going to try promoting someone else, see if that works. Noipe, this doesn't work for me.

**Comment by Iridar** [comment]
> It wasn't this mod, it was a conflict of other mods that caused a CTD whenpromoting various soldiers. It is mods left over from when I last played WotC, and tried Long War otC. And I had mod conflicts.

Closing.
