### ISSUE TITLE
Game softlocks on promotion screen during Tutorial

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2CommunityPromotionScreen#83]
When you first promote Jane Kelly. This may or may not be connected to "hide "new class" popup" MCM Setting.

**Comment by Hellrespawn** [comment]
I can confirm I've had the same issue, and indeed narrowed it down to having "Disable New Class popups" checked while doing the tutorial.

**Comment by Iridar** [comment]
Confirmed by testing. I'll make CPS ignore the MCM setting while tutorial is active.
